framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
    router:
        utf8: true
    validation:
        email_validation_mode: html5
        auto_mapping:
            App\Entity\: []
    session:
        handler_id: null # Use default session handler
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native