services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'
    Symfony\Bridge\Doctrine\ArgumentResolver\EntityValueResolver: ~
    Symfony\Component\Security\Csrf\CsrfTokenManagerInterface: '@security.csrf.token_manager'